var judge = require('../calculate.js');
var assert = require("assert"); // 引入内置的assert模块
describe("国际普通行李计算-超重，不超尺寸", function() {
    it("区域一 1件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:0,type_line:3,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:17};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:35};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(0, judge(passenger1,baggage1,special_bagg));
    });
    it("区域一 1件超重，不超尺寸 super经济舱超重", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:2,type_line:3,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:24};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(1780, judge(passenger1,baggage1,special_bagg));
    });
    it("区域一 1件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:0,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:12};
        var data2 = {len:80,wide:50,high:10,weight:26};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        var special_bagg = [];
        assert.equal(2070, judge(passenger1,baggage1,special_bagg));
    });
    it("区域一 1件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:3,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:26};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(1780, judge(passenger1,baggage1,special_bagg));
    });

    it("区域二 1件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:0,type_line:1,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:21};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:37};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(0, judge(passenger1,baggage1,special_bagg));
    });
    it("区域二 1件超重，不超尺寸 super经济舱超重", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:2,type_line:1,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:25};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(1280, judge(passenger1,baggage1,special_bagg));
    });
    it("区域二 1件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:1,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:25};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        var special_bagg = [];
        assert.equal(1280, judge(passenger1,baggage1,special_bagg));
    });
    it("区域二 1件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:4,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:26};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(1280, judge(passenger1,baggage1,special_bagg));
    });

    it("区域三 1件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:0,type_line:0,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:19};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:33};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(0, judge(passenger1,baggage1,special_bagg));
    });
    it("区域三 1件超重，不超尺寸 super经济舱超重", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:2,type_line:0,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:26};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(2070, judge(passenger1,baggage1,special_bagg));
    });
    it("区域三 1件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:0,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:26};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        var special_bagg = [];
        assert.equal(2070, judge(passenger1,baggage1,special_bagg));
    });
    it("区域三 1件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:0,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:25};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(3450, judge(passenger1,baggage1,special_bagg));
    });

    it("区域四 1件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:0,type_line:2,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:14};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:38};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(0, judge(passenger1,baggage1,special_bagg));
    });
    it("区域四 1件超重，不超尺寸 super经济舱超重", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:2,type_line:2,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:24};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(1040, judge(passenger1,baggage1,special_bagg));
    });
    it("区域四 1件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:2,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:26};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        var special_bagg = [];
        assert.equal(1040, judge(passenger1,baggage1,special_bagg));
    });
    it("区域四 1件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger1 ={type_flight:1,type_ticket:0,type_cabin:3,type_line:5,price:1500};
        var data1 = {len:80,wide:50,high:10,weight:18};
        var data2 = {len:80,wide:50,high:10,weight:20};
        var data3 = {len:80,wide:50,high:10,weight:27};
        var baggage1 = new Array();
        baggage1[0] = data1;
        baggage1[1] = data2;
        baggage1[2] = data3;
        var special_bagg = [];
        assert.equal(1040, judge(passenger1,baggage1,special_bagg));
    });


    it("区域一 2件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:3};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:35};
        var data4 = {len:70,wide:50,high:10,weight:35};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域一 2件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:3};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(4160, judge(passenger,baggage,special_bagg));
    });
    it("区域一 2件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:24};
        var data3 = {len:70,wide:50,high:10,weight:24};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        var special_bagg = [];
        assert.equal(4140, judge(passenger,baggage,special_bagg));
    });
    it("区域一 2件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:26};
        var data4 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(5730, judge(passenger,baggage,special_bagg));
    });

    it("区域二 2件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:1};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:37};
        var data4 = {len:70,wide:50,high:10,weight:36};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域二 2件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:1};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:24};
        var data4 = {len:70,wide:50,high:10,weight:25};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(2560, judge(passenger,baggage,special_bagg));
    });
    it("区域二 2件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:1};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:26};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        var special_bagg = [];
        assert.equal(2560, judge(passenger,baggage,special_bagg));
    });
    it("区域二 2件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:4};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:24};
        var data4 = {len:70,wide:50,high:10,weight:25};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(2560, judge(passenger,baggage,special_bagg));
    });
    
    it("区域三 2件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:34};
        var data4 = {len:70,wide:50,high:10,weight:33};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域三 2件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(4140, judge(passenger,baggage,special_bagg));
    });
    it("区域三 2件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:26};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        var special_bagg = [];
        assert.equal(4140, judge(passenger,baggage,special_bagg));
    });
    it("区域三 2件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(5730, judge(passenger,baggage,special_bagg));
    });

    it("区域四 2件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:2};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:35};
        var data4 = {len:70,wide:50,high:10,weight:34};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域四 2件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:2};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:26};
        var data4 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(2350, judge(passenger,baggage,special_bagg));
    });
    it("区域四 2件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:2};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:25};
        var data3 = {len:70,wide:50,high:10,weight:24};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        var special_bagg = [];
        assert.equal(2350, judge(passenger,baggage,special_bagg));
    });
    it("区域四 2件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:5};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:26};
        var data4 = {len:70,wide:50,high:10,weight:25};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(2350, judge(passenger,baggage,special_bagg));
    });

    it("区域一 3件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:3};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:35};
        var data4 = {len:70,wide:50,high:10,weight:36};
        var data5 = {len:70,wide:50,high:10,weight:34};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域一 3件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:3};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(7540, judge(passenger,baggage,special_bagg));

    });
    it("区域一 3件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:3};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(4160, judge(passenger,baggage,special_bagg));
    });
    it("区域一 3件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:3};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(7540, judge(passenger,baggage,special_bagg));
    });

    it("区域二 3件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:1};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:35};
        var data4 = {len:70,wide:50,high:10,weight:36};
        var data5 = {len:70,wide:50,high:10,weight:37};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域二 3件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:1};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(3940, judge(passenger,baggage,special_bagg));
    });
    it("区域二 3件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:1};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(3760, judge(passenger,baggage,special_bagg));
    });
    it("区域二 3件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:4};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(3940, judge(passenger,baggage,special_bagg));
    });
    
    it("区域三 3件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:34};
        var data4 = {len:70,wide:50,high:10,weight:35};
        var data5 = {len:70,wide:50,high:10,weight:37};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域三 3件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(6420, judge(passenger,baggage,special_bagg));
    });
    it("区域三 3件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:24};
        var data4 = {len:70,wide:50,high:10,weight:25};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(5730, judge(passenger,baggage,special_bagg));
    });
    it("区域三 3件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:0};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(8010, judge(passenger,baggage,special_bagg));
    });

    it("区域四 3件超重，不超尺寸 头等舱/公务舱", function(){
        var passenger ={type_flight:1,type_cabin:0,type_line:2};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:35};
        var data4 = {len:70,wide:50,high:10,weight:34};
        var data5 = {len:70,wide:50,high:10,weight:35};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(0, judge(passenger,baggage,special_bagg));
    });
    it("区域四 3件超重，不超尺寸 super经济舱超重", function(){
        var passenger ={type_flight:1,type_cabin:2,type_line:2};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(4150, judge(passenger,baggage,special_bagg));
    });
    it("区域四 3件超重，不超尺寸 普通经济舱超重 路线第一类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:2};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:25};
        var data4 = {len:70,wide:50,high:10,weight:24};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        var special_bagg = [];
        assert.equal(3940, judge(passenger,baggage,special_bagg));
    });
    it("区域四 3件超重，不超尺寸 普通经济舱超重 路线第二类", function(){
        var passenger ={type_flight:1,type_cabin:3,type_line:5};
        var data1 = {len:70,wide:50,high:10,weight:18};
        var data2 = {len:70,wide:50,high:10,weight:20};
        var data3 = {len:70,wide:50,high:10,weight:24};
        var data4 = {len:70,wide:50,high:10,weight:25};
        var data5 = {len:70,wide:50,high:10,weight:26};
        var baggage = new Array();
        baggage[0] = data1;
        baggage[1] = data2;
        baggage[2] = data3;
        baggage[3] = data4;
        baggage[4] = data5;
        var special_bagg = [];
        assert.equal(4150, judge(passenger,baggage,special_bagg));
    });

});
